name: ogusa-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7,<3.12
- numpy
- numba>=0.54
- scipy>=1.5.0
- pandas>=1.2.5
- matplotlib
- dask>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- taxcalc>=3.0.0
- sphinx>=3.5.4
- sphinx-book-theme>=0.1.3
- pip
- pytest>=6.0
- pytest-cov
- pytest-xdist
- pylint
- coverage
- requests
- xlwt
- statsmodels
- linearmodels
- rpy2<=3.5.11
- black>=24.1.1
- pip:
  - jupyter-book>=0.9.1
  - openpyxl>=3.1.2
  - cs-kit
  - cs2tc
  - pandas-datareader
  - ogcore
